#include "enums.h"

const std::map<PASSIVE_NAME, std::string> STRINGS::PASSIVE_NAME_MAP = {
	{ PASSIVE_NAME::NONE, "NONE" },

	{ PASSIVE_NAME::SWIFT_ASSASSIN, "SWIFT_ASSASSIN" },
	{ PASSIVE_NAME::STEADY_HAND, "STEADY_HAND" },
	{ PASSIVE_NAME::GUILE, "GUILE" },
	{ PASSIVE_NAME::EVASION, "EVASION" },
	{ PASSIVE_NAME::AGILITY, "AGILITY" },

	{ PASSIVE_NAME::CLOAK_OF_SHADOWS, "CLOAK_OF_SHADOWS" },
	{ PASSIVE_NAME::PURSUIT, "PURSUIT" },

	{ PASSIVE_NAME::FOCUS_FIRE, "FOCUS_FIRE" },
	{ PASSIVE_NAME::ASSASSINS_QUIVER, "ASSASSINS_QUIVER" },
	{ PASSIVE_NAME::MISSILE_MASTERY, "MISSILE_MASTERY" },
	{ PASSIVE_NAME::CONCENTRATION, "CONCENTRATION" },
	{ PASSIVE_NAME::WOUND_MAKER, "WOUND_MAKER" },
	{ PASSIVE_NAME::HEIGHTENED_SENCES, "HEIGHTENED_SENCES" },

	{ PASSIVE_NAME::HANDLER, "HANDLER" },
	{ PASSIVE_NAME::AGILE_HUNT, "AGILE_HUNT" },
	{ PASSIVE_NAME::RANGERS_MARK, "RANGERS_MARK" },
	{ PASSIVE_NAME::TACTITIAN, "TACTITIAN" },
	{ PASSIVE_NAME::COORDINATED_FADE, "COORDINATED_FADE" },
	{ PASSIVE_NAME::EVASION_TACTICS, "EVASION_TACTICS" },
	{ PASSIVE_NAME::INTUITIVE_CONNECTION, "INTUITIVE_CONNECTION" },
	{ PASSIVE_NAME::RELENTLESS_TALONS, "RELENTLESS_TALONS" },
	{ PASSIVE_NAME::NEEDLE_LIKE_PRECISION, "NEEDLE_LIKE_PRECISION" },
	{ PASSIVE_NAME::EXPEDIENCY, "EXPEDIENCY" },
	{ PASSIVE_NAME::FINESSE_THEM, "FINESSE_THEM" },
	{ PASSIVE_NAME::TAILWIND, "TAILWIND" },
};

const std::map<PASSIVE_CLASS_NAME, std::string> STRINGS::PASSIVE_CLASS_NAME_MAP = {
	{ PASSIVE_CLASS_NAME::BASE, "BASE" },
	{ PASSIVE_CLASS_NAME::BLADEDANCER, "BLADEDANCER" },
	{ PASSIVE_CLASS_NAME::MARKSMAN, "MARKSMAN" },
	{ PASSIVE_CLASS_NAME::FALCONER, "FALCONER" },
};

const std::map<ITEM_TYPE, std::string> STRINGS::ITEM_TYPE_MAP = {
	{ ITEM_TYPE::HELM, "HELM" },
	{ ITEM_TYPE::AMULET, "AMULET" },
	{ ITEM_TYPE::BOW, "BOW" },
	{ ITEM_TYPE::QUIVER, "QUIVER" },
	{ ITEM_TYPE::BODY, "BODY" },
	{ ITEM_TYPE::RING, "RING" },
	{ ITEM_TYPE::BELT, "BELT" },
	{ ITEM_TYPE::GLOVES, "GLOVES" },
	{ ITEM_TYPE::BOOTS, "BOOTS" },
	{ ITEM_TYPE::RELIC, "RELIC" },
	{ ITEM_TYPE::BIG_IDOL, "BIG_IDOL" },
	{ ITEM_TYPE::SMALL_IDOL, "SMALL_IDOL" },
};

const std::map<SKILL_PASSIVE_NAME, std::string> STRINGS::SKILL_PASSIVE_NAME_MAP = {
	{ SKILL_PASSIVE_NAME::NONE_, "NONE" },

	{ SKILL_PASSIVE_NAME::AGILE_ENGENEERING, "AGILE_ENGENEERING" },
	{ SKILL_PASSIVE_NAME::EFFICIENT_CONSTRUCTION, "EFFICIENT_CONSTRUCTION" },
	{ SKILL_PASSIVE_NAME::PRACTICAL_BUILD, "PRACTICAL_BUILD" },
	{ SKILL_PASSIVE_NAME::LIGHT_BOLTS, "LIGHT_BOLTS" },
	{ SKILL_PASSIVE_NAME::SHARPENED_TIPS, "SHARPENED_TIPS" },
	{ SKILL_PASSIVE_NAME::PERFECT_AIM, "PERFECT_AIM" },
	{ SKILL_PASSIVE_NAME::TWINNED_BOLTS, "TWINNED_BOLTS" },
	{ SKILL_PASSIVE_NAME::HEAVY_BOLTS, "HEAVY_BOLTS" },
	{ SKILL_PASSIVE_NAME::SHARED_ENHANCEMENTS, "SHARED_ENHANCEMENTS" },
	{ SKILL_PASSIVE_NAME::RAPID_FIRE, "RAPID_FIRE" },
	{ SKILL_PASSIVE_NAME::CONTAMINATING_SHOTS, "CONTAMINATING_SHOTS" },
	{ SKILL_PASSIVE_NAME::STURDY_FOUNDATION, "STURDY_FOUNDATION" },
	{ SKILL_PASSIVE_NAME::CARE_PACKAGE, "CARE_PACKAGE" },
	{ SKILL_PASSIVE_NAME::ELIXIR_OF_CONSTRUCTION, "ELIXIR_OF_CONSTRUCTION" },
};